import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DisableDevTools from "@/components/DisableDevTools";

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-poppins",
  subsets: ["latin"], // Poppins usually only supports latin and devanagari officially
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased font-sans`}>
        <DisableDevTools />
        {children}
      </body>
    </html >
  );
}
