import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DisableDevTools from "@/components/DisableDevTools";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
        <DisableDevTools />
        {children}
      </body>
    </html>
  );
}
